export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const ADD_CART_ITEM_FAILURE = "ADD_CART_ITEM_FAILURE";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const REMOVE_CART_ITEM_FAILURE = "REMOVE_CART_ITEM_FAILURE";

export const CART_SAVE_SHIPPING = "CART_SAVE_SHIPPING";
export const CART_SAVE_PAYMENT = "CART_SAVE_PAYMENT";
